#!/usr/bin/env python3
"""
parse_rom.py — convert a RISC-V objdump disassembly into rom_dump.v.

Usage:
    python3 parse_rom.py <objdump.txt> [rom_dump.v]

The input is standard objdump -d output:
      0:	fe010113          	addi	sp,sp,-32

The output is a synthesizable Verilog combinational ROM module that
cpu.v instantiates and streams into RAM during reset.
"""

import sys
import re
import struct

# objdump -d:  "   0:  fe010113  addi sp,sp,-32"
_INSTR_RE = re.compile(r'^\s+([0-9a-f]+):\s+([0-9a-f]{8})\b')
# objdump -s:  " 03d0 66697273 74202028 ..."  (bytes in address order, 4 per group)
_SECT_RE  = re.compile(r'^ ([0-9a-f]+) ((?:[0-9a-f]{8} *)+)')


def parse(path):
    # dict deduplicates; -d values (seen first) take priority for .text
    words = {}
    with open(path) as f:
        for line in f:
            m = _INSTR_RE.match(line)
            if m:
                addr = int(m.group(1), 16)
                word = int(m.group(2), 16)
                words.setdefault(addr, word)
                continue
            m = _SECT_RE.match(line)
            if m:
                base = int(m.group(1), 16)
                for i, grp in enumerate(m.group(2).split()):
                    if len(grp) == 8:   # skip incomplete trailing groups
                        w = struct.unpack('<I', bytes.fromhex(grp))[0]
                        words.setdefault(base + i * 4, w)
    return sorted(words.items())


def emit(words, src, dst):
    nwords = len(words)
    lines = []
    lines.append('// Auto-generated by parse_rom.py — do not edit')
    lines.append(f'// Source: {src}')
    lines.append(f'// Words: {nwords}')
    lines.append('')
    lines.append('module rom_dump (')
    lines.append('    input  wire [31:0] word_idx,')
    lines.append('    output reg  [31:0] data,')
    lines.append('    output reg  [31:0] addr,')
    lines.append('    output wire        valid')
    lines.append(');')
    lines.append('')
    lines.append(f'localparam NWORDS = {nwords};')
    lines.append('')
    lines.append('assign valid = (word_idx < NWORDS);')
    lines.append('')
    lines.append('always @(*) begin')
    lines.append('    case (word_idx)')
    for i, (byte_addr, word) in enumerate(words):
        lines.append(f"        32'd{i}: begin data = 32'h{word:08X}; addr = 32'h{byte_addr:08X}; end")
    lines.append("        default: begin data = 32'h00000000; addr = 32'h00000000; end")
    lines.append('    endcase')
    lines.append('end')
    lines.append('')
    lines.append('endmodule')

    with open(dst, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'Wrote {dst}  ({nwords} words)')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(f'Usage: {sys.argv[0]} <objdump.txt> [rom_dump.v]')
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else 'rom_dump.v'
    words = parse(src)
    if not words:
        sys.exit('No instructions found — check input format')
    emit(words, src, dst)
